/*
Copyright [2014] - [2023] The Last.Backend authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package templates

// GitIgnore is the .gitignore template used for new services.
var GitIgnore = `# This file generated by toolkit CLI.
# Binaries for programs and plugins
# Develop tools
/.vscode/
/.idea/

# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Folders
_obj
_test
_build

# Architecture specific extensions/prefixes
*.[568vq]
[568vq].out

*.cgo1.go
*.cgo2.c
_cgo_defun.c
_cgo_gotypes.go
_cgo_export.*

# Test binary, build with 'go test -c'
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# vim temp files
*~
*.swp
*.swo

# Ignore the service binary to vcs
{{.Service}}
`
