// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protoc-gen-toolkit/toolkit/options/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runtime_Server int32

const (
	Runtime_GRPC            Runtime_Server = 0
	Runtime_HTTP            Runtime_Server = 1
	Runtime_WEBSOCKET_PROXY Runtime_Server = 2
	Runtime_WEBSOCKET       Runtime_Server = 3
)

// Enum value maps for Runtime_Server.
var (
	Runtime_Server_name = map[int32]string{
		0: "GRPC",
		1: "HTTP",
		2: "WEBSOCKET_PROXY",
		3: "WEBSOCKET",
	}
	Runtime_Server_value = map[string]int32{
		"GRPC":            0,
		"HTTP":            1,
		"WEBSOCKET_PROXY": 2,
		"WEBSOCKET":       3,
	}
)

func (x Runtime_Server) Enum() *Runtime_Server {
	p := new(Runtime_Server)
	*p = x
	return p
}

func (x Runtime_Server) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runtime_Server) Descriptor() protoreflect.EnumDescriptor {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_enumTypes[0].Descriptor()
}

func (Runtime_Server) Type() protoreflect.EnumType {
	return &file_protoc_gen_toolkit_toolkit_options_annotations_proto_enumTypes[0]
}

func (x Runtime_Server) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runtime_Server.Descriptor instead.
func (Runtime_Server) EnumDescriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{2, 0}
}

type Plugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Plugin) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *Plugin) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Package       string                 `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Service) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*Plugin              `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Servers       []Runtime_Server       `protobuf:"varint,2,rep,packed,name=servers,proto3,enum=toolkit.Runtime_Server" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Runtime) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *Runtime) GetServers() []Runtime_Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type TestSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mockery       *MockeryTestsSpec      `protobuf:"bytes,1,opt,name=mockery,proto3" json:"mockery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSpec) Reset() {
	*x = TestSpec{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSpec) ProtoMessage() {}

func (x *TestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSpec.ProtoReflect.Descriptor instead.
func (*TestSpec) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *TestSpec) GetMockery() *MockeryTestsSpec {
	if x != nil {
		return x.Mockery
	}
	return nil
}

type MockeryTestsSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockeryTestsSpec) Reset() {
	*x = MockeryTestsSpec{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockeryTestsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockeryTestsSpec) ProtoMessage() {}

func (x *MockeryTestsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockeryTestsSpec.ProtoReflect.Descriptor instead.
func (*MockeryTestsSpec) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *MockeryTestsSpec) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Middlewares   []string               `protobuf:"bytes,1,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *Server) GetMiddlewares() []string {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

type Route struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Middlewares              []string               `protobuf:"bytes,1,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	ExcludeGlobalMiddlewares []string               `protobuf:"bytes,2,rep,name=exclude_global_middlewares,json=excludeGlobalMiddlewares,proto3" json:"exclude_global_middlewares,omitempty"`
	// Types that are valid to be assigned to Server:
	//
	//	*Route_HttpProxy
	//	*Route_WebsocketProxy
	//	*Route_Websocket
	Server        isRoute_Server `protobuf_oneof:"server"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *Route) GetMiddlewares() []string {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *Route) GetExcludeGlobalMiddlewares() []string {
	if x != nil {
		return x.ExcludeGlobalMiddlewares
	}
	return nil
}

func (x *Route) GetServer() isRoute_Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Route) GetHttpProxy() *HttpProxy {
	if x != nil {
		if x, ok := x.Server.(*Route_HttpProxy); ok {
			return x.HttpProxy
		}
	}
	return nil
}

func (x *Route) GetWebsocketProxy() *WsProxy {
	if x != nil {
		if x, ok := x.Server.(*Route_WebsocketProxy); ok {
			return x.WebsocketProxy
		}
	}
	return nil
}

func (x *Route) GetWebsocket() bool {
	if x != nil {
		if x, ok := x.Server.(*Route_Websocket); ok {
			return x.Websocket
		}
	}
	return false
}

type isRoute_Server interface {
	isRoute_Server()
}

type Route_HttpProxy struct {
	HttpProxy *HttpProxy `protobuf:"bytes,3,opt,name=http_proxy,json=httpProxy,proto3,oneof"`
}

type Route_WebsocketProxy struct {
	WebsocketProxy *WsProxy `protobuf:"bytes,4,opt,name=websocket_proxy,json=websocketProxy,proto3,oneof"`
}

type Route_Websocket struct {
	Websocket bool `protobuf:"varint,5,opt,name=websocket,proto3,oneof"`
}

func (*Route_HttpProxy) isRoute_Server() {}

func (*Route_WebsocketProxy) isRoute_Server() {}

func (*Route_Websocket) isRoute_Server() {}

type HttpProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpProxy) Reset() {
	*x = HttpProxy{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpProxy) ProtoMessage() {}

func (x *HttpProxy) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpProxy.ProtoReflect.Descriptor instead.
func (*HttpProxy) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *HttpProxy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HttpProxy) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type WsProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsProxy) Reset() {
	*x = WsProxy{}
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsProxy) ProtoMessage() {}

func (x *WsProxy) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsProxy.ProtoReflect.Descriptor instead.
func (*WsProxy) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{8}
}

func (x *WsProxy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WsProxy) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

var file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*Plugin)(nil),
		Field:         50001,
		Name:          "toolkit.plugins",
		Tag:           "bytes,50001,rep,name=plugins",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*Service)(nil),
		Field:         50002,
		Name:          "toolkit.services",
		Tag:           "bytes,50002,rep,name=services",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*TestSpec)(nil),
		Field:         50004,
		Name:          "toolkit.tests_spec",
		Tag:           "bytes,50004,opt,name=tests_spec",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Runtime)(nil),
		Field:         70001,
		Name:          "toolkit.runtime",
		Tag:           "bytes,70001,opt,name=runtime",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Server)(nil),
		Field:         70002,
		Name:          "toolkit.server",
		Tag:           "bytes,70002,opt,name=server",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Route)(nil),
		Field:         60001,
		Name:          "toolkit.route",
		Tag:           "bytes,60001,opt,name=route",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// repeated toolkit.Plugin plugins = 50001;
	E_Plugins = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[0]
	// repeated toolkit.Service services = 50002;
	E_Services = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[1]
	// optional toolkit.TestSpec tests_spec = 50004;
	E_TestsSpec = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional toolkit.Runtime runtime = 70001;
	E_Runtime = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[3]
	// optional toolkit.Server server = 70002;
	E_Server = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[4]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional toolkit.Route route = 60001;
	E_Route = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[5]
)

var File_protoc_gen_toolkit_toolkit_options_annotations_proto protoreflect.FileDescriptor

const file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc = "" +
	"\n" +
	"4protoc-gen-toolkit/toolkit/options/annotations.proto\x12\atoolkit\x1a google/protobuf/descriptor.proto\"8\n" +
	"\x06Plugin\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"=\n" +
	"\aService\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\"\xa9\x01\n" +
	"\aRuntime\x12)\n" +
	"\aplugins\x18\x01 \x03(\v2\x0f.toolkit.PluginR\aplugins\x121\n" +
	"\aservers\x18\x02 \x03(\x0e2\x17.toolkit.Runtime.ServerR\aservers\"@\n" +
	"\x06Server\x12\b\n" +
	"\x04GRPC\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\x13\n" +
	"\x0fWEBSOCKET_PROXY\x10\x02\x12\r\n" +
	"\tWEBSOCKET\x10\x03\"?\n" +
	"\bTestSpec\x123\n" +
	"\amockery\x18\x01 \x01(\v2\x19.toolkit.MockeryTestsSpecR\amockery\",\n" +
	"\x10MockeryTestsSpec\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\"*\n" +
	"\x06Server\x12 \n" +
	"\vmiddlewares\x18\x01 \x03(\tR\vmiddlewares\"\x83\x02\n" +
	"\x05Route\x12 \n" +
	"\vmiddlewares\x18\x01 \x03(\tR\vmiddlewares\x12<\n" +
	"\x1aexclude_global_middlewares\x18\x02 \x03(\tR\x18excludeGlobalMiddlewares\x123\n" +
	"\n" +
	"http_proxy\x18\x03 \x01(\v2\x12.toolkit.HttpProxyH\x00R\thttpProxy\x12;\n" +
	"\x0fwebsocket_proxy\x18\x04 \x01(\v2\x10.toolkit.WsProxyH\x00R\x0ewebsocketProxy\x12\x1e\n" +
	"\twebsocket\x18\x05 \x01(\bH\x00R\twebsocketB\b\n" +
	"\x06server\"=\n" +
	"\tHttpProxy\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\";\n" +
	"\aWsProxy\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method:I\n" +
	"\aplugins\x12\x1c.google.protobuf.FileOptions\x18ц\x03 \x03(\v2\x0f.toolkit.PluginR\aplugins:L\n" +
	"\bservices\x12\x1c.google.protobuf.FileOptions\x18҆\x03 \x03(\v2\x10.toolkit.ServiceR\bservices:P\n" +
	"\n" +
	"tests_spec\x12\x1c.google.protobuf.FileOptions\x18Ԇ\x03 \x01(\v2\x11.toolkit.TestSpecR\ttestsSpec:M\n" +
	"\aruntime\x12\x1f.google.protobuf.ServiceOptions\x18\xf1\xa2\x04 \x01(\v2\x10.toolkit.RuntimeR\aruntime:J\n" +
	"\x06server\x12\x1f.google.protobuf.ServiceOptions\x18\xf2\xa2\x04 \x01(\v2\x0f.toolkit.ServerR\x06server:F\n" +
	"\x05route\x12\x1e.google.protobuf.MethodOptions\x18\xe1\xd4\x03 \x01(\v2\x0e.toolkit.RouteR\x05routeBOZMgithub.com/lastbackend/toolkit/protoc-gen-toolkit/toolkit/options;annotationsb\x06proto3"

var (
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescOnce sync.Once
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescData []byte
)

func file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP() []byte {
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescOnce.Do(func() {
		file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc), len(file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc)))
	})
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescData
}

var file_protoc_gen_toolkit_toolkit_options_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protoc_gen_toolkit_toolkit_options_annotations_proto_goTypes = []any{
	(Runtime_Server)(0),                 // 0: toolkit.Runtime.Server
	(*Plugin)(nil),                      // 1: toolkit.Plugin
	(*Service)(nil),                     // 2: toolkit.Service
	(*Runtime)(nil),                     // 3: toolkit.Runtime
	(*TestSpec)(nil),                    // 4: toolkit.TestSpec
	(*MockeryTestsSpec)(nil),            // 5: toolkit.MockeryTestsSpec
	(*Server)(nil),                      // 6: toolkit.Server
	(*Route)(nil),                       // 7: toolkit.Route
	(*HttpProxy)(nil),                   // 8: toolkit.HttpProxy
	(*WsProxy)(nil),                     // 9: toolkit.WsProxy
	(*descriptorpb.FileOptions)(nil),    // 10: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 11: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 12: google.protobuf.MethodOptions
}
var file_protoc_gen_toolkit_toolkit_options_annotations_proto_depIdxs = []int32{
	1,  // 0: toolkit.Runtime.plugins:type_name -> toolkit.Plugin
	0,  // 1: toolkit.Runtime.servers:type_name -> toolkit.Runtime.Server
	5,  // 2: toolkit.TestSpec.mockery:type_name -> toolkit.MockeryTestsSpec
	8,  // 3: toolkit.Route.http_proxy:type_name -> toolkit.HttpProxy
	9,  // 4: toolkit.Route.websocket_proxy:type_name -> toolkit.WsProxy
	10, // 5: toolkit.plugins:extendee -> google.protobuf.FileOptions
	10, // 6: toolkit.services:extendee -> google.protobuf.FileOptions
	10, // 7: toolkit.tests_spec:extendee -> google.protobuf.FileOptions
	11, // 8: toolkit.runtime:extendee -> google.protobuf.ServiceOptions
	11, // 9: toolkit.server:extendee -> google.protobuf.ServiceOptions
	12, // 10: toolkit.route:extendee -> google.protobuf.MethodOptions
	1,  // 11: toolkit.plugins:type_name -> toolkit.Plugin
	2,  // 12: toolkit.services:type_name -> toolkit.Service
	4,  // 13: toolkit.tests_spec:type_name -> toolkit.TestSpec
	3,  // 14: toolkit.runtime:type_name -> toolkit.Runtime
	6,  // 15: toolkit.server:type_name -> toolkit.Server
	7,  // 16: toolkit.route:type_name -> toolkit.Route
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	11, // [11:17] is the sub-list for extension type_name
	5,  // [5:11] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protoc_gen_toolkit_toolkit_options_annotations_proto_init() }
func file_protoc_gen_toolkit_toolkit_options_annotations_proto_init() {
	if File_protoc_gen_toolkit_toolkit_options_annotations_proto != nil {
		return
	}
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[6].OneofWrappers = []any{
		(*Route_HttpProxy)(nil),
		(*Route_WebsocketProxy)(nil),
		(*Route_Websocket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc), len(file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_toolkit_toolkit_options_annotations_proto_goTypes,
		DependencyIndexes: file_protoc_gen_toolkit_toolkit_options_annotations_proto_depIdxs,
		EnumInfos:         file_protoc_gen_toolkit_toolkit_options_annotations_proto_enumTypes,
		MessageInfos:      file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes,
		ExtensionInfos:    file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes,
	}.Build()
	File_protoc_gen_toolkit_toolkit_options_annotations_proto = out.File
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_goTypes = nil
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_depIdxs = nil
}
