// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: protoc-gen-toolkit/toolkit/options/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin string `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Plugin) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *Plugin) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Package string `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Client) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Client) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type DockerfileSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expose          []int32  `protobuf:"varint,1,rep,packed,name=expose,proto3" json:"expose,omitempty"`
	Commands        []string `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	RewriteIfExists bool     `protobuf:"varint,3,opt,name=rewrite_if_exists,json=rewriteIfExists,proto3" json:"rewrite_if_exists,omitempty"`
}

func (x *DockerfileSpec) Reset() {
	*x = DockerfileSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerfileSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerfileSpec) ProtoMessage() {}

func (x *DockerfileSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerfileSpec.ProtoReflect.Descriptor instead.
func (*DockerfileSpec) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *DockerfileSpec) GetExpose() []int32 {
	if x != nil {
		return x.Expose
	}
	return nil
}

func (x *DockerfileSpec) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *DockerfileSpec) GetRewriteIfExists() bool {
	if x != nil {
		return x.RewriteIfExists
	}
	return false
}

type TestSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mockery *MockeryTestsSpec `protobuf:"bytes,1,opt,name=mockery,proto3" json:"mockery,omitempty"`
}

func (x *TestSpec) Reset() {
	*x = TestSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSpec) ProtoMessage() {}

func (x *TestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSpec.ProtoReflect.Descriptor instead.
func (*TestSpec) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *TestSpec) GetMockery() *MockeryTestsSpec {
	if x != nil {
		return x.Mockery
	}
	return nil
}

type MockeryTestsSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
}

func (x *MockeryTestsSpec) Reset() {
	*x = MockeryTestsSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockeryTestsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockeryTestsSpec) ProtoMessage() {}

func (x *MockeryTestsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockeryTestsSpec.ProtoReflect.Descriptor instead.
func (*MockeryTestsSpec) Descriptor() ([]byte, []int) {
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *MockeryTestsSpec) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

var file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*Plugin)(nil),
		Field:         50001,
		Name:          "toolkit.plugins",
		Tag:           "bytes,50001,rep,name=plugins",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*Client)(nil),
		Field:         50002,
		Name:          "toolkit.clients",
		Tag:           "bytes,50002,rep,name=clients",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*DockerfileSpec)(nil),
		Field:         50003,
		Name:          "toolkit.dockerfile_spec",
		Tag:           "bytes,50003,opt,name=dockerfile_spec",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*TestSpec)(nil),
		Field:         50004,
		Name:          "toolkit.tests_spec",
		Tag:           "bytes,50004,opt,name=tests_spec",
		Filename:      "protoc-gen-toolkit/toolkit/options/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// repeated toolkit.Plugin plugins = 50001;
	E_Plugins = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[0]
	// repeated toolkit.Client clients = 50002;
	E_Clients = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[1]
	// optional toolkit.DockerfileSpec dockerfile_spec = 50003;
	E_DockerfileSpec = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[2]
	// optional toolkit.TestSpec tests_spec = 50004;
	E_TestsSpec = &file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes[3]
)

var File_protoc_gen_toolkit_toolkit_options_annotations_proto protoreflect.FileDescriptor

var file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc = []byte{
	0x0a, 0x34, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x74, 0x6f, 0x6f,
	0x6c, 0x6b, 0x69, 0x74, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x38, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x3c, 0x0a, 0x06, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x70, 0x0a, 0x0e, 0x44, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x78, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x65, 0x78, 0x70,
	0x6f, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12,
	0x2a, 0x0a, 0x11, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x66, 0x5f, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x72, 0x65, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x49, 0x66, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x3f, 0x0a, 0x08, 0x54,
	0x65, 0x73, 0x74, 0x53, 0x70, 0x65, 0x63, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x6b,
	0x69, 0x74, 0x2e, 0x4d, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x79, 0x54, 0x65, 0x73, 0x74, 0x73, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x07, 0x6d, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x79, 0x22, 0x2c, 0x0a, 0x10,
	0x4d, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x79, 0x54, 0x65, 0x73, 0x74, 0x73, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x3a, 0x49, 0x0a, 0x07, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x07, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x73, 0x3a, 0x49, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2,
	0x86, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x3a, 0x60, 0x0a, 0x0f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xd3, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x6f, 0x6f, 0x6c,
	0x6b, 0x69, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x0e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x3a, 0x50, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x70, 0x65, 0x63,
	0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd4,
	0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x09, 0x74, 0x65, 0x73, 0x74, 0x73,
	0x53, 0x70, 0x65, 0x63, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x73, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x74,
	0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69,
	0x74, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescOnce sync.Once
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescData = file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc
)

func file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescGZIP() []byte {
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescOnce.Do(func() {
		file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescData)
	})
	return file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDescData
}

var file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protoc_gen_toolkit_toolkit_options_annotations_proto_goTypes = []interface{}{
	(*Plugin)(nil),                   // 0: toolkit.Plugin
	(*Client)(nil),                   // 1: toolkit.Client
	(*DockerfileSpec)(nil),           // 2: toolkit.DockerfileSpec
	(*TestSpec)(nil),                 // 3: toolkit.TestSpec
	(*MockeryTestsSpec)(nil),         // 4: toolkit.MockeryTestsSpec
	(*descriptorpb.FileOptions)(nil), // 5: google.protobuf.FileOptions
}
var file_protoc_gen_toolkit_toolkit_options_annotations_proto_depIdxs = []int32{
	4, // 0: toolkit.TestSpec.mockery:type_name -> toolkit.MockeryTestsSpec
	5, // 1: toolkit.plugins:extendee -> google.protobuf.FileOptions
	5, // 2: toolkit.clients:extendee -> google.protobuf.FileOptions
	5, // 3: toolkit.dockerfile_spec:extendee -> google.protobuf.FileOptions
	5, // 4: toolkit.tests_spec:extendee -> google.protobuf.FileOptions
	0, // 5: toolkit.plugins:type_name -> toolkit.Plugin
	1, // 6: toolkit.clients:type_name -> toolkit.Client
	2, // 7: toolkit.dockerfile_spec:type_name -> toolkit.DockerfileSpec
	3, // 8: toolkit.tests_spec:type_name -> toolkit.TestSpec
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	5, // [5:9] is the sub-list for extension type_name
	1, // [1:5] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoc_gen_toolkit_toolkit_options_annotations_proto_init() }
func file_protoc_gen_toolkit_toolkit_options_annotations_proto_init() {
	if File_protoc_gen_toolkit_toolkit_options_annotations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerfileSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockeryTestsSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_toolkit_toolkit_options_annotations_proto_goTypes,
		DependencyIndexes: file_protoc_gen_toolkit_toolkit_options_annotations_proto_depIdxs,
		MessageInfos:      file_protoc_gen_toolkit_toolkit_options_annotations_proto_msgTypes,
		ExtensionInfos:    file_protoc_gen_toolkit_toolkit_options_annotations_proto_extTypes,
	}.Build()
	File_protoc_gen_toolkit_toolkit_options_annotations_proto = out.File
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_rawDesc = nil
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_goTypes = nil
	file_protoc_gen_toolkit_toolkit_options_annotations_proto_depIdxs = nil
}
